#!/usr/bin/env python3
"""
Pauli to j algorithm test script (PennyLane compatible).
Delegates to mub/pauli_to_j.py.
"""


from src.pauli_to_j import (
    pauli_to_xz,
    solve_j,
    p_to_j,
    run_mub_orthogonality_test,
)

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Run MUB Pauli stabilizer orthogonality test.")
    parser.add_argument("-n", "--qubits", type=int, default=3, help="Number of qubits (default: 3)")
    parser.add_argument("-v", "--verbose", action="store_true", help="Verbose output")
    args = parser.parse_args()

    run_mub_orthogonality_test(args.qubits, verbose=args.verbose)
